version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
  web:
    build: .
    command: >
      /bin/bash -c "
        while ! curl -X GET elasticsearch:9200/_cluster/health --silent;
        do
          sleep 2;
        done;
        python manage.py load foods.txt
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch